### ISSUE TITLE
global name 'run_func' is not defined

### ISSUE THREAD

**Issue by xiaoyongzhu** [yongxuUSTC/dcase2017_task4_cvssp#1]
I am trying to replicate the result, but looks like there is one issue when running the "recognize" part. The main_crnn_sed.py file throws out an exception, saying run_func is not defined:

`Traceback (most recent call last):
  File "main_crnn_sed.py", line 291, in <module>
    recognize(args, at_bool=True, sed_bool=True)
  File "main_crnn_sed.py", line 176, in recognize
    pred3d = run_func(func_loc_output, x, batch_size=64)
NameError: global name 'run_func' is not defined`

Looks like run_func is not a function in any library, so I assume this is some function that is not included in the repository?

**Comment by qiuqiangkong** [comment]
Many thanks! The bug is fixed! Please let us know if you have further problems!
